### ISSUE TITLE
Couldn't install pyqt4 on ubuntu!

### ISSUE THREAD

**Issue by akomaty** [1900zyh/3D-Human-Body-Shape#20]
Hello,

I am wondering if your code could be used on a Linux machine?
Because I tried to install pyqt4 and didn't manage to do it unfortunately!

**Comment by 1900zyh** [comment]
Hi, thank you for your interest. 
I have tried it and it works well on windows/OSX/Linux with python3.5.

**Comment by akomaty** [comment]
Thank you for your fast response!
In fact, I am struggling with the pyqt4 install on Ubuntu.
When I am trying to install the requirements using pip:
```
pip install -r requirements.txt
```
The install goes fine for all the packages **except** for the `pyqt4` and I get the following error:
```
ERROR: Could not find a version that satisfies the requirement pyqt4==4.11.4 (from -r requirements.txt (line 12)) (from versions: none)
ERROR: No matching distribution found for pyqt4==4.11.4 (from -r requirements.txt (line 12))
```
After searching on the internet for a solution on the website https://www.riverbankcomputing.com/static/Docs/PyQt4/installation.html
I tried following the steps (compiling `sip` from source then trying to compile `pyqt4`), I was getting always error when running `make` and `make install`. The error is as follows:

```
/home/akomaty/Documents/work/Project_Bassel/software/py-virtual-env/PyQt4_gpl_x11-4.12.3/QtCore/sipQtCoreQAbstractEventDispatcher.cpp:115:10: error: ‘void sipQAbstractEventDispatcher::registerTimer(int, int, QObject*)’ marked ‘override’, but does not override
     void registerTimer(int,int, ::QObject*) SIP_OVERRIDE;
          ^~~~~~~~~~~~~
Makefile:18: recipe for target 'sipQtCoreQAbstractEventDispatcher.o' failed
make[1]: *** [sipQtCoreQAbstractEventDispatcher.o] Error 1
make[1]: Leaving directory '/home/akomaty/Documents/work/Project_Bassel/software/py-virtual-env/PyQt4_gpl_x11-4.12.3/QtCore'
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2
```

According to all the above, my only problem is with installing the last requirement in your `requirements.txt` file. Could you please let me know how you installed pyqt4 version 4.11.4 on ubuntu?

Best regards,
Alain

**Comment by 1900zyh** [comment]
Hi Alain,
I remember that I installed pyqt4 on ubuntu simply by commands (not limited to version 4.11.4, you can tried other versions). possible solution: https://www.saltycrane.com/blog/2008/01/how-to-install-pyqt4-on-ubuntu-linux/

Or you can try on this pull request by using PyQt5:
https://github.com/1900zyh/3D-Human-Body-Shape/pull/19

Best regards,
Yanhong

**Comment by grig8693** [comment]
Hello)

I have a question about upgrading program (I have python 3.7.5 and PyQt5), but when i try to install all libs from requirements, there are lots of mistakes
[Errors.docx](https://github.com/1900zyh/3D-Human-Body-Shape/files/4209983/Errors.docx)

I dowload VS 2019, i try to install from requirements .txt from  https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4
but nothing changes... I cant find any solution

**Comment by 1900zyh** [comment]
Hi @grig8693 
Sorry for my late reply. I have merged a pull request that works on pyqt5. 
You can try the latest version of master branch. 
I have tested it with pyqt5 and python3.5, on macOS.

**Comment by grig8693** [comment]
Thank u so much)) Ohh its okay, i use Windows machine (sry i'm not pro in
knowing computers). I use python 3.7.5 and pyqt5) I have an idea to make
free program for making custom leather clothes and in this case i write u
for help:) I dont wanna use progs like Clo3d or Marwelous design. I think
that people can wear cool clothes and also wear everyting that they want
and they must do that absolutly free :D (i read 2 month ago cool book 'bout
money, Bernard Lietar)

вс, 23 февр. 2020 г., 5:40 zyh <notifications@github.com>:

**Comment by 1900zyh** [comment]
Hi @grig8693,
The idea is very interesting and helpful!
However, I'm sorry that I have no plan and no time to go further on this project.
I hope everything goes well with you!

Thanks,

**Comment by grig8693** [comment]
Thank u too :)

вс, 23 февр. 2020 г., 11:43 zyh <notifications@github.com>:
